### PR TITLE
Fixed Issue 2785 - Wireframe renderer broken with CAM data

### LINKED ISSUE #2785: Wireframe renderer broken with CAM data
A regression has been introduced that causes the WireFrame renderer to assert.

To reproduce:
1. Load CAM/AdamPhillips/F2000C5_new120_025/FV_768x1152.bilinear.F2000C5_new120_025.cam.h0.2004-01.nc
2. Create a wireframe renderer, selected 2D variables, and enable

vapor terminates with:

VAssert(coords.size() == dims.size()) failed in utils.cpp, line 45
Terminated

### PR DESCRIPTION
**Pull request by clyne**
Fixed #2785 

Refactored Grid iterators to use std::array instead of std:vector, making the iterators consistent with the rest of the Grid API

### CODE REVIEW

File: lib/vdc/CurvilinearGrid.cpp [hunk 1]
```diff
@@ -237,14 +237,14 @@ CurvilinearGrid::ConstCoordItrCG::ConstCoordItrCG(const CurvilinearGrid *cg, boo
...
 
     if (ndims == 3) {
         if (_terrainFollowing) {
-            _coords.push_back(*_zCoordItr);
+            _coords[2] = *_zCoordItr;
         } else {
-            _coords.push_back(_cg->_zcoords[0]);
+            _coords[2] = _cg->_zcoords[0];
         }
     }
```
Comment (shaomeng) [inline lib/vdc/CurvilinearGrid.cpp:249]: Should give _coords[2] a default value in condition of ndims != 3, right?

**Review by shaomeng — COMMENTED** [review]
Just a small improvement needed :)

File: lib/vdc/CurvilinearGrid.cpp (hunk 1 above)
Comment (clyne) [reply lib/vdc/CurvilinearGrid.cpp:250]: Fixed

File: lib/vdc/CurvilinearGrid.cpp [hunk 2]
```diff
@@ -314,28 +315,28 @@ void CurvilinearGrid::ConstCoordItrCG::next()
...
     auto ndims = _cg->GetNumDimensions();
 
-    vector<size_t> maxIndex;
-    maxIndex.reserve(3);
+    if (!ndims) return;
+
+    DimsType maxIndex = {0, 0, 0};
 
-    for (int i = 0; i < ndims; i++) maxIndex.push_back(dims[i] - 1);
+    for (int i = 0; i < ndims; i++) maxIndex[i] = dims[i] - 1;
```
Comment (shaomeng) [inline lib/vdc/CurvilinearGrid.cpp:326]: There are many instances where `dims[i] - 1` is assigned to another variable of unsigned int type. There's a danger when `dims[i]` holds 0, then nobody knows what `dims[i] - 1` will be. 

I think based on the knowledge of how likely that situation can occur, asserts can be inserted in some instances.

**Review by shaomeng — APPROVED** [review]

File: lib/vdc/CurvilinearGrid.cpp (hunk 2 above)
Comment (shaomeng) [reply lib/vdc/CurvilinearGrid.cpp:326]: Though this is something not related to this PR, so feel free to not deal with it.

File: lib/render/ContourRenderer.cpp [hunk 3]
```diff
@@ -116,7 +116,11 @@ int ContourRenderer::_buildCache()
     double mv = grid->GetMissingValue();
     float  Z0 = GetDefaultZ(_dataMgr, _cacheParams.ts);
 
-    Grid::ConstCellIterator it = grid->ConstCellBegin(_cacheParams.boxMin, _cacheParams.boxMax);
+    CoordType boxMin = {0.0, 0.0, 0.0};
+    CoordType boxMax = {0.0, 0.0, 0.0};
+    Grid::CopyToArr3(_cacheParams.boxMin, boxMin);
+    Grid::CopyToArr3(_cacheParams.boxMax, boxMax);
+    Grid::ConstCellIterator it = grid->ConstCellBegin(boxMin, boxMax);
```
Comment (StasJ) [inline lib/render/ContourRenderer.cpp:123]: Instead of having to repeat this process every time we want to get a grid, couldn't `ConstCellBegin` be overloaded to support vectors? Especially since `Box` still returns vectors.

File: lib/vdc/CurvilinearGrid.cpp (hunk 2 above)
Comment (clyne) [reply lib/vdc/CurvilinearGrid.cpp]: You can never have to many asserts IMHO :-). Done.

File: lib/render/ContourRenderer.cpp (hunk 3 above)
Comment (clyne) [reply lib/render/ContourRenderer.cpp]: Indeed. Done.

**Review by StasJ — APPROVED** [review]
