### PR TITLE
Fix problems regarding the Slicer's Box

### LINKED ISSUE #2971: Slice crash
SliceGridAlongPlane() will crash when the Box extents of a slice renderer lie outside of the slice plane.

To reproduce:
1) Create a Slice renderer with any dataset
2) Rotate it by 90 degrees on the X axis
3) Move the box so its extents are outside of the slice plane.  Vapor will crash.

### PR DESCRIPTION
**Pull request by sgpearse**
Fixes #2971 and #2968.

#2969 is still a work in progress, but my work on it will be based on top of these two fixes.

### CODE REVIEW

File: include/vapor/SliceGridAlongPlane.h [hunk 1]
```diff
@@ -8,10 +8,13 @@
 class RegularGrid;
 
 struct planeDescription {
+    size_t sideSize;
     std::vector<double> origin;
     std::vector<double> rotation;
     VAPoR::CoordType boxMin;
     VAPoR::CoordType boxMax;
+    VAPoR::CoordType domainMin;
+    VAPoR::CoordType domainMax;
```
Comment (StasJ) [inline include/vapor/SliceGridAlongPlane.h:17]: The 3D `Grid` passed into `SliceGridAlongPlane` already has the function `Grid::GetUserExtents` which returns the data extents. Could that just be used rather than passing around this parameter here?

Comment (sgpearse) [reply include/vapor/SliceGridAlongPlane.h:17]: No, and this is reason why #2968 happened.

The SliceRenderer requests a 3D grid based on the SliceRenderer's Box.  When a new Grid is created, its extents can differ from the Box extents that it is fed because some nodes get clipped off.

The fix here is to use a set of domain and box extents that are not derived from the passed 3D grid.

**Review by StasJ — APPROVED** [review]

File: lib/render/SliceRenderer.cpp [hunk 2]
```diff
@@ -140,6 +136,16 @@ void SliceRenderer::_resetCache()
 
     _getExtents(_cacheParams.boxMin, _cacheParams.boxMax);
 
+    // clang-format off
+    _dataMgr->GetVariableExtents(_cacheParams.ts,
```
Comment (clyne) [inline lib/render/SliceRenderer.cpp:140]: It looks like you are getting the variable extents here (_cacheParams.domainMin, _cacheParams.domainMax), and the only place you are using them is to pass them into SliceGridAlongPlane(), which also takes a grid3d argument. Why not simply call grid3d->GetUserExtents() from inside SliceGridAlongPlane()? The results should be identical, and it would simplify the code a good bit.

File: lib/render/SliceRenderer.cpp [hunk 3]
```diff
@@ -173,11 +179,15 @@ int SliceRenderer::_regenerateSlice()
...
+    pd.sideSize = _textureSideSize;
     pd.origin = {_cacheParams.xOrigin, _cacheParams.yOrigin, _cacheParams.zOrigin};
     pd.rotation = {_cacheParams.xRotation, _cacheParams.yRotation, _cacheParams.zRotation};
     pd.boxMin = _cacheParams.boxMin;
     pd.boxMax = _cacheParams.boxMax;
-    RegularGrid *slice = SliceGridAlongPlane(grid3d, pd, _textureSideSize, dataValues, _windingOrder, _rectangle3D);
+    pd.domainMin = _cacheParams.domainMin;
+    pd.domainMax = _cacheParams.domainMax;
+    RegularGrid *slice = SliceGridAlongPlane(grid3d, pd, dataValues, _windingOrder, _rectangle3D);
+    if (slice == nullptr) return 0;
```
Comment (clyne) [inline lib/render/SliceRenderer.cpp:190]: Isn't this an error condition? Shouldn't it be returning -1, not 0?

File: lib/vdc/SliceGridAlongPlane.cpp [hunk 4]
```diff
@@ -163,7 +168,15 @@ void populateData(
             double y = yStart + i*delta.y;
             glm::tvec3<double, glm::highp> samplePoint = origin + x*axis1 + y*axis2;
             VAPoR::CoordType p = {samplePoint.x, samplePoint.y, samplePoint.z};
-            dataValues.get()[index] = grid->GetValue(p);
+
+            if ( p[0] <= min[0] || p[0] >= max[0] ||
```
Comment (clyne) [inline lib/vdc/SliceGridAlongPlane.cpp:172]: Are you finding it necessary to explicitly compare p with the extents of the Grid object? Grid::GetValue(p) should return missingValue if p is outside of the domain.If it is not then there is a bug that should be reported.

File: lib/render/SliceRenderer.cpp (hunk 2 above)
Comment (sgpearse) [reply lib/render/SliceRenderer.cpp:140]: This is because I need the full extents of a variable, not the extents of the current Grid, which may have had its region reduced.

The promise that the SliceGridAlongPlane makes is that it samples a variable along a plane throughout the entire domain.  Samples that are outside of the Box are counted as missingValues.  What I'm doing here might be a little unclear, so I'll write a note below discussing the strategy.

File: lib/render/SliceRenderer.cpp (hunk 3 above)
Comment (sgpearse) [reply lib/render/SliceRenderer.cpp:190]: Yes. I missed cleaning this up while debugging.  Fixed.

File: lib/vdc/SliceGridAlongPlane.cpp (hunk 4 above)
Comment (sgpearse) [reply lib/vdc/SliceGridAlongPlane.cpp:172]: This is checking whether the sample point is outside of the Box, no the domain.

File: include/vapor/SliceGridAlongPlane.h (hunk 1 above)
Comment (clyne) [reply include/vapor/SliceGridAlongPlane.h:17]: Got it

File: lib/render/SliceRenderer.cpp (hunk 2 above)
Comment (clyne) [reply lib/render/SliceRenderer.cpp:140]: Got it.

File: lib/vdc/SliceGridAlongPlane.cpp (hunk 4 above)
Comment (clyne) [reply lib/vdc/SliceGridAlongPlane.cpp:172]: Understood. Since both @StasJ and I were confused about this and explicit comment might be helpful.

A small nit, perhaps, but do you really want to (need to) exclude points on the boundary (e.g. using <= instead of <)? I doubt that we are completely consistent about this, and in most instances it may not matter, but I think elsewhere points that are on the boundary are considered "valid".

Comment (sgpearse) [reply lib/vdc/SliceGridAlongPlane.cpp:172]: Yes, I agree and I'm going to write something up to put in the file.

I can go ahead and remove the '='.  These were added during debugging.  They had no effect but weren't removed.

**Comment by sgpearse** [comment]
@clyne and @StasJ - here's some context to my strategy for these bugs.  I've added a summary of this in SliceGridAlongPlane.h.

The SliceRenderer was crashing when the Box and plane did not intersect.  This was happening because the returned 2D grid was only being sampled within the bounds of the current Box.  When the plane and Box did not intersect the returned grid would be invalid, causing a crash.  

One option was to add logic in the SliceRenderer to handle this special case, however this option would require every renderer using SliceGridAlongPlane() to handle it as well.  

The alternative I chose was to have SliceGridAlongPlane() return a valid grid in this case.  The returned grid would be sampled along a given plane, and would have missingValues at points that do not lie within the Box.  The Slice and Contour logic would be simplified by letting them operate on the returned grid in the same way, whether there are valid values or not.

Note that I am using the domain extents gathered from the DataMgr, and the Box extents from RenderParams.  I'm not using the extents gathered from the 3D grid because those can be in disagreement with the DataMgr and RenderParams.  This occurs due to roundoff whenever the Grid's extents are reduced, which incrementally reduces the Grid's dimension lengths.

Hope that makes sense.

**Review by clyne — APPROVED** [review]
