### PR TITLE
fix nan comparison

### LINKED ISSUE #3087: Flow renderer crashes on NetCDF data
To reproduce:
1) Import the three NetCDF files in /glade/p/cisl/vast/vapor/Bugs/3087
2) Create  flow renderer and select Bx as the X field variable
3) Enable the renderer, vapor will crash

### PR DESCRIPTION
**Pull request by shaomeng**
fix

f5df70909abc081425143f3664579ce4ef35e90a: [clangTidyOutput.txt](https://output.circle-artifacts.com/output/job/838aa6f4-a1a3-45af-89bc-934217a46e8c/artifacts/0/tmp/clangTidyOutput.txt)

### CODE REVIEW

File: lib/flow/VaporField.cpp [hunk 1]
```diff
@@ -237,10 +237,15 @@ int VaporField::GetVelocity(double time, const glm::vec3 &pos, glm::vec3 &veloci
             missingV[i] = grid->GetMissingValue();
         }
         auto  hasMissing = glm::equal(velocity, missingV);
+        // If missing values are represented using NaN, you cannot compare equality with them!
```
Comment (clyne) [inline lib/flow/VaporField.cpp:240]: One small nit: missing values should NEVER be represented as NaNs because, as you say, you can't compare them. The NaN's must be either either in the existing data or generated by the interpolation somehow.

Comment (shaomeng) [reply lib/flow/VaporField.cpp:240]: I think it's from the specific data set in this case. I.e., `grid->GetMissingValue()` would return you a nan... Does this header look like it's using nan? 

```
netcdf test_bx_vapor {
dimensions:
	time = 1 ;
	x = 168 ;
	y = 93 ;
	z = 46 ;
variables:
	double Bx(time, x, y, z) ;
		Bx:_FillValue = NaN ;
		Bx:units = "G" ;
	double time(time) ;
		time:_FillValue = NaN ;
		time:axis = "T" ;
		time:units = "seconds since 2000-0101" ;
	double x(x) ;
		x:_FillValue = NaN ;
		x:axis = "Z" ;
		x:units = "m" ;
	double y(y) ;
		y:_FillValue = NaN ;
		y:axis = "Y" ;
		y:units = "m" ;
	double z(z) ;
		z:_FillValue = NaN ;
		z:axis = "X" ;
		z:units = "m" ;
}
```

File: lib/flow/Advection.cpp [hunk 2]
```diff
@@ -678,7 +678,7 @@ float Advection::_applyPeriodic(float val, float min, float max) const
 
 void Advection::_printNonZero(int rtn, const char *file, const char *func, int line) const
 {
-#ifdef VPRINT
+#ifndef NDEBUG
```
Comment (StasJ) [inline lib/flow/Advection.cpp:681]: Prints hundreds of debug lines that are probably not necessary for every debug build.

File: lib/flow/VaporField.cpp [hunk 3]
```diff
@@ -237,10 +237,15 @@ int VaporField::GetVelocity(double time, const glm::vec3 &pos, glm::vec3 &veloci
...
+        for (int i = 0; i < 3; i++) {
+          if (std::isnan(missingV[i]) && velocity[i])
```
Comment (StasJ) [inline lib/flow/VaporField.cpp:242]: I would try and avoid implicitly converting float to bool.

**Review by StasJ — CHANGES_REQUESTED** [review]

File: lib/flow/Advection.cpp (hunk 2 above)
Comment (shaomeng) [reply lib/flow/Advection.cpp:681]: Well, I wasn't able to print out hundreds of lines debug output, but it's reverted in 3e4e4c7b0 .

File: lib/flow/VaporField.cpp (hunk 3 above)
Comment (shaomeng) [reply lib/flow/VaporField.cpp]: Good catch! It was a typo and is fixed in be4afab5c .

File: lib/flow/VaporField.cpp (hunk 1 above)
Comment (clyne) [reply lib/flow/VaporField.cpp:240]: You are correct. I thought using NaNs for missing values were prohibited by the CF conventions, but that is not the case. Unfortunately, this means that there are several other places in the code that should be changed to handle missing values that are NaNs. I will open an issue.

**Review by clyne — APPROVED** [review]

File: lib/flow/Advection.cpp (hunk 2 above)
Comment (StasJ) [reply lib/flow/Advection.cpp]: Might've been my session file. Thanks.

**Review by StasJ — APPROVED** [review]

**Comment by clyne** [comment]
@shaomeng will merge as soon as passing checks.

**Comment by shaomeng** [comment]
> @shaomeng will merge as soon as passing checks.

Could @sgpearse suggest why circle ci is failing, and how to fix? This PR touched 2 cpp files, but circle ci fails on python.
