### PR TITLE
Fixed  #2462 - redo broken

### LINKED ISSUE #2462: Redo broken
1. Do something
2. Undo it

Redo is greyed out.

### PR DESCRIPTION
**Pull request by clyne**
Fixed  #2462

### CODE REVIEW

File: lib/vdc/CurvilinearGrid.cpp [hunk 1]
```diff
@@ -312,7 +312,9 @@ CurvilinearGrid::ConstCoordItrCG::ConstCoordItrCG(
 	_xCoordItr = rhs._xCoordItr;
 	_yCoordItr = rhs._yCoordItr;
 	_zCoordItr = rhs._zCoordItr;
-	_terrainFollowing = rhs._terrainFollowing;
+	if (rhs._terrainFollowing) {
+		_terrainFollowing = rhs._terrainFollowing;
+	}
```
Comment (StasJ) [inline lib/vdc/CurvilinearGrid.cpp:317]: This seems unrelated

File: lib/render/ControlExecutive.cpp [hunk 2]
```diff
@@ -160,12 +160,12 @@ int ControlExec::Paint(string winName, bool fast){
...
 	//
-	bool enabled = _paramsMgr->GetSaveStateUndoEnabled();
-	_paramsMgr->SetSaveStateUndoEnabled(false);
+	bool enabled = _paramsMgr->GetSaveStateEnabled();
+	_paramsMgr->SetSaveStateEnabled(false);
 
 	int rc =  v->paintEvent(fast);
 
-	_paramsMgr->SetSaveStateUndoEnabled(enabled);
+	_paramsMgr->SetSaveStateEnabled(enabled);
```
Comment (StasJ) [inline lib/render/ControlExecutive.cpp:168]: This will reintroduce #2418. I would assume the proper fix is to prevent changes performed when undo is disabled from clearing the redo list.

**Review by StasJ — CHANGES_REQUESTED** [review]

File: lib/vdc/CurvilinearGrid.cpp (hunk 1 above)
Comment (clyne) [reply lib/vdc/CurvilinearGrid.cpp:317]: It is. I'm not sure how this snuck in here, but it does fix a memory access error.

File: lib/render/ControlExecutive.cpp (hunk 2 above)
Comment (clyne) [reply lib/render/ControlExecutive.cpp:168]: I'm not sure what the "proper" fix is, but if you want to modify SetSaveStateUndoEnabled per your description we can try it.

Comment (StasJ) [reply lib/render/ControlExecutive.cpp:168]: I checked and this does not reintroduce that bug. After some head scratching I think I figured out why this is. Also I checked and preventing the redo list from clearing when undo is disabled fixes the issue as well, however I am not familiar enough with this code to say which is the proper fix.

**Review by StasJ — APPROVED** [review]

File: lib/render/ControlExecutive.cpp (hunk 2 above)
Comment (clyne) [reply lib/render/ControlExecutive.cpp:168]: Yeah, undo/redo needs some work. I've opened a ticket to do some refactoring. Hopefully the latest bandaid will get us through the release.
