### PR TITLE
Fixed #2346 - Build fails on CentOS

### LINKED ISSUE #2346: Build fails on CentOS
Our build is currently failing on CentOS on cisl-garibaldi.cisl.ucar.edu, as well as our CircleCI build.

```
In file included from /home/pearse/VAPOR/lib/vdc/Grid.cpp:18:0:
/home/pearse/VAPOR/include/vapor/Grid.h:1432:2: error: array must be initialized with a brace-enclosed initializer
  };
  ^
/home/pearse/VAPOR/include/vapor/Grid.h:1432:2: error: too many initializers for ‘VAPoR::DblArr3 {aka std::array<double, 3ul>}’
/home/pearse/VAPOR/include/vapor/Grid.h:1437:2: error: array must be initialized with a brace-enclosed initializer
  };
  ^
/home/pearse/VAPOR/include/vapor/Grid.h:1437:2: error: too many initializers for ‘VAPoR::DblArr3 {aka std::array<double, 3ul>}’
make[2]: *** [lib/vdc/CMakeFiles/vdc.dir/Grid.cpp.o] Error 1
make[1]: *** [lib/vdc/CMakeFiles/vdc.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by clyne**

### CODE REVIEW

File: apps/vaporgui/MainForm.h [hunk 1]
```diff
@@ -35,6 +35,7 @@
 #include <QIcon>
 #include <QLineEdit>
 #include <QWidgetAction>
+#include <chrono>
```
Comment (sgpearse) [inline apps/vaporgui/MainForm.h:38]: Maybe Git is being funky here.  Could this be something from the progress bar branch?

Comment (clyne) [reply apps/vaporgui/MainForm.h:38]: I had to add that to get it to compile on garibaldi
