### PR TITLE
fix 3306 - Problems with ZFP compression on OSX

### LINKED ISSUE #3306: ZFP compressed NetCDF files do NOT open with VAPOR 3.7.0
### Describe the bug
NetCDF4 files using ZFP compression throw a "NetCDF: Unimplemented Filter" error when trying to access properly encoded ZFP compressed CF compliant NetCDF4/HDF5 files.

I am much of the impetus behind this welcome code change of having VAPOR natively read NetCDF4 files that are ZFP compressed. However on the Mac M1 version, it just doesn't work. I tried mucking with HDF5_PLUGIN_PATH (thinking that perhaps it had to be set) but to no avail.
[vaporlog.txt](https://github.com/NCAR/VAPOR/files/10320536/vaporlog.txt)

### PR DESCRIPTION
**Pull request by sgpearse**
Fixes #3306 ZFP issues by bypassing the use of H5PLreplace() in favor of just setting the HDF5_PLUGIN_PATH environment variable in the current process.

### CODE REVIEW

**Review by StasJ — APPROVED** [review]

File: include/vapor/SetHDF5PluginPath.h [hunk 1]
```diff
@@ -3,20 +3,16 @@
...
-    #include <H5PLpublic.h>
-#endif
-
 namespace VAPoR {
 void SetHDF5PluginPath() {
-    string plugins = Wasp::GetSharePath("plugins");
-
-    #ifndef WIN32
-        H5PLreplace(plugins.c_str(), 0);
+    int rc;
```
Comment (shaomeng) [inline include/vapor/SetHDF5PluginPath.h:8]: Good software engineering practice: not to leave a variable not initialized.
Suggested change: int rc = 0;

**Review by shaomeng — APPROVED** [review]

File: include/vapor/SetHDF5PluginPath.h (hunk 1 above)
Comment (sgpearse) [reply include/vapor/SetHDF5PluginPath.h]: Gotcha.
