### PR TITLE
Issue2821: Tighter constraints on TIME token, and relevant documentation

### LINKED ISSUE #2821: BOV: not supporting implicit multiple time steps
To reproduce: 
1) Open VAPOR.
2) Import 2 BOV files representing 2 time steps: 
`/glade/p/cisl/vast/vapor/Bugs/BOV_Bugs/bug7.bov` and `/glade/p/cisl/vast/vapor/Bugs/BOV_Bugs/bug8.bov`.
3) Create a renderer. Notice that VAPOR shows there's only one time step.

### PR DESCRIPTION
**Pull request by sgpearse**
Fixes #2821 by making the TIME token mandatory in each file, and throwing an error when duplicate files refer to a single variable at the same timestep.

Also adds documentation on how this requirement for TIME, and adds info on default values for the optional tokens in BOV files.

### CODE REVIEW

File: lib/vdc/BOVCollection.cpp [hunk 1]
```diff
@@ -123,8 +124,13 @@ int BOVCollection::Initialize(const std::vector<std::string> &paths)
             if (_dataFile == _defaultFile) { return _missingValueError(DATA_FILE_TOKEN); }
             if (_dataFormat == _defaultFormat) { return _missingValueError(FORMAT_TOKEN); }
             if (_gridSize == _defaultGridSize) { return _missingValueError(GRID_SIZE_TOKEN); }
+            if (_time == _defaultTime) { return _missingValueError(TIME_TOKEN); }
 
-            _populateDataFileMap();
+            rc = _populateDataFileMap();
```
Comment (clyne) [inline lib/vdc/BOVCollection.cpp:129]: It would be better to have the error message inside of _populateDataFileMap() for a couple of reasons:

1. Our error reporting convention states that functions that return a negative int on failure should report an error with SetErrMsg() (prefer a boolean return status for functions that do NOT report a message).
2. Better future proofing: if some other error condition gets added to _populateDataFileMap() later the current error message may not make sense.

**Review by clyne — APPROVED** [review]

**Review by shaomeng — APPROVED** [review]
