### PR TITLE
Fix #2418 Flow: Streamline data file can only be written once

### LINKED ISSUE #2418: Flow: Streamline data file can only be written once
I seem to only be able to write the flow streamline .csv once.

To reproduce on OSX:
1. Delete ~/VaporFlow.txt
2. Create a default flow renderer, and write VaporFlow.txt with the first variable in the list (P in DUKU's case)
3. Note the time of day that the file was written
4. Wait a minute and try to write the file again.  The timestamp does not update

### PR DESCRIPTION
**Pull request by StasJ**
Fix #2418

Fixed the bug by removing code that prevented changes to the params database from occurring from within a paint event. This would in the past have caused other bugs but I previously put checks in place that prevent paint events from queueing recursively.

Also added a mechanism for non-undoable actions which the write to file button now uses. This is also now automatically applied to all params changes from within a paint event since these are only supposed to be a side effect of an action the user performed in the GUI which will be undoable.

### CODE REVIEW

File: apps/vaporgui/PButton.h [hunk 1]
```diff
@@ -16,10 +16,13 @@ class PButton : public PWidget {
     typedef std::function<void(VAPoR::ParamsBase*)> Callback;
     VPushButton *_button;
     const Callback _cb;
+    bool _disableUndo = false;
 public:
     PButton(std::string label, Callback cb);
+    PButton *DisableUndo();
```
Comment (clyne) [inline apps/vaporgui/PButton.h:22]: Please document.

File: include/vapor/ParamsMgr.h [hunk 2]
```diff
@@ -508,6 +508,12 @@ class PARAMS_API ParamsMgr : public MyBase {
  }
 
  bool GetSaveStateEnabled() const { return (_ssave.GetEnabled()); }
+
```
Comment (clyne) [inline include/vapor/ParamsMgr.h:511]: Please document {Get,Set}SaveStateUndoEnabled AND {Get,Set}SaveStateEnabled so we have a clear understanding of what these closely related methods do and when you might use one versus the other.

**Review by clyne — COMMENTED** [review]
Nice work, @stasj. I 've left a couple of in-line comments and have a couple of questions.

1. Does this PR resolve the problem we discussed yesterday where parameter changes were not being excepted by the Params data base?

2. It seems like having the ControlExec::Paint() method as the only method that the UI can use to interact with the renderers is becoming a real limitation, forcing us to do unnatural things like image capture, output of flow lines, etc. from within Renderer::_paintGL. Perhaps it's time to think about adding something like pre and post paint methods that could be triggered to perform these non-rendering tasks. What are your thoughts?

**Review by sgpearse — COMMENTED** [review]
It's bizarre to me, but my QFileDialog still does not let me specify a filename.  We all saw Stas demonstrate this functionality yesterday.  

I've checked out issue2418 and have rebuilt from scratch, but I still don't see a way to enter a file name.  I'm testing on OSX 10.14.6.

@stasj I'll review this more tomorrow morning on some other platforms.  Could you share which OSX version you used to demonstrate the fix yesterday?

Screen Shot 2020-11-12 at 3 22 49 PM

**Comment by StasJ** [comment]
> It's bizarre to me, but my QFileDialog still does not let me specify a filename. We all saw Stas demonstrate this functionality yesterday.
> 
> I've checked out issue2418 and have rebuilt from scratch, but I still don't see a way to enter a file name. I'm testing on OSX 10.14.6.
> 
> @StasJ I'll review this more tomorrow morning on some other platforms. Could you share which OSX version you used to demonstrate the fix yesterday?

@sgpearse Odd. I used Mojave.

File: include/vapor/ParamsMgr.h (hunk 2 above)
Comment (StasJ) [reply include/vapor/ParamsMgr.h:511]: I documented {Get,Set}SaveStateUndoEnabled.

I did not write the {Get,Set}SaveStateEnabled functions and I don’t know what they are supposed to do. Based on the resulting behavior I am assuming their functionality is broken.

File: apps/vaporgui/PButton.h (hunk 1 above)
Comment (StasJ) [reply apps/vaporgui/PButton.h:23]: Done

**Comment by StasJ** [comment]
> Nice work, @StasJ. I 've left a couple of in-line comments and have a couple of questions.
> 
> 1. Does this PR resolve the problem we discussed yesterday where parameter changes were not being excepted by the Params data base?

Yes

> 2. It seems like having the ControlExec::Paint() method as the only method that the UI can use to interact with the renderers is becoming a real limitation, forcing us to do unnatural things like image capture, output of flow lines, etc. from within Renderer::_paintGL. Perhaps it's time to think about adding something like pre and post paint methods that could be triggered to perform these non-rendering tasks. What are your thoughts?

I agree that some other mechanism for performing non-rendering tasks would be useful although it may likely require significant refactoring.

File: include/vapor/ParamsMgr.h (hunk 2 above)
Comment (clyne) [reply include/vapor/ParamsMgr.h:511]: Well then let's either fix the older function or replace it, But let's not have two methods that are ostensibly supposed to provide the same functionality but for some reason are not.

Comment (StasJ) [reply include/vapor/ParamsMgr.h:511]: Well I can’t fix it if I don’t know what it’s supposed to do. For the same reason I also didn’t know that they are supposed to have the same functionality. I can look into whether we can simply remove/replace the old function since it is broken anyway but since it is so old there may be code that depends on its odd behavior.

Comment (StasJ) [reply include/vapor/ParamsMgr.h:511]: It seems to be used in multiple places and based on the context in which it is used I don't think my new function provides the intended functionality of the old function.

**Comment by sgpearse** [comment]
@stasj my bad.  

I'm getting a core dump when I write the file multiple times with different variables.  But I think this problem lies outside of this bug, so I'll write a new bug and approve.

**Review by sgpearse — APPROVED** [review]

File: include/vapor/ParamsMgr.h (hunk 2 above)
Comment (clyne) [reply include/vapor/ParamsMgr.h:511]: I'm going to approve this, but I've opened a ticket to address (refactor) some of the uglyness that is going on with state saving: #2444

**Review by clyne — APPROVED** [review]
