### PR TITLE
fix #2768

### LINKED ISSUE #2768: Regression introduced by #2752
There appears to be a regression introduced by #2752 when invoking the wireframe renderer. 

To reproduce:
1. Load /glade/p/cisl/vast/vapor/data/Source/DKRZ-Ocean/gr15/gr15_uvw_vis.nc
2. Enable a wireframe renderer. vapor will crash

### PR DESCRIPTION
**Pull request by shaomeng**
This PR fixes issue #2768.

The effort spent here, together with effort spent on PR #2752 , will turn out to be completely useless once issue #2765 is properly addressed. This exercise demonstrates the wasteful nature of addressing issues half-way by applying band-aids, and it's something we should avoid in the future.

### CODE REVIEW

File: lib/vdc/ConstantGrid.cpp [hunk 1]
```diff
@@ -39,14 +39,14 @@ std::vector<size_t> ConstantGrid::GetCoordDimensions(size_t) const
 
 size_t ConstantGrid::GetGeometryDim() const { return 3; }
 
-const std::vector<size_t> &ConstantGrid::GetNodeDimensions() const
+const std::array<size_t, 3> ConstantGrid::GetNodeDimensions() const
```
Comment (clyne) [inline lib/vdc/ConstantGrid.cpp:42]: Please use Size_tArr3 for the type.

File: include/vapor/ConstantGrid.h [hunk 2]
```diff
@@ -50,30 +50,29 @@ class VDF_API ConstantGrid : public Grid {
     // They do nothing and return meaningless values.
     // Do not use!
     //
-    std::vector<size_t>        GetCoordDimensions(size_t) const override;
```
Comment (clyne) [inline include/vapor/ConstantGrid.h:53]: Any idea why all of this code changed?

**Review by clyne — COMMENTED** [review]
A couple of nits

File: include/vapor/Grid.h [hunk 3]
```diff
@@ -1209,6 +1210,16 @@ class VDF_API Grid {
         }
     }
 
+    virtual void ClampIndex(const std::array<size_t, 3> &dims, size_t nNodeDims, const Size_tArr3 indices, Size_tArr3 &cIndices) const
+    {
+        cIndices = {0, 0, 0};
+
+        for (int i = 0; i < nNodeDims; i++) {
```
[the remark this answers is not in the document]
Comment (shaomeng) [reply include/vapor/Grid.h:1217]: well, I don't understand the logic of the task performed here, so I wrote it in a way that's equivalent to the old code. If you can tell me that it will do the right thing even when the length is fixed to 3, then I can definitely remove the length parameter.

File: include/vapor/ConstantGrid.h (hunk 2 above)
Comment (shaomeng) [reply include/vapor/ConstantGrid.h:53]: clang-format did it

File: lib/vdc/ConstantGrid.cpp (hunk 1 above)
Comment (shaomeng) [reply lib/vdc/ConstantGrid.cpp:42]: Well, this alias is so confusing---it *appears* to be using both camel case and underscore conventions simultaneously within 10 letters. How about we use the C++ standard name for this PR and wait the alias to be fixed to be less confusing later?

File: include/vapor/Grid.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (clyne) [reply include/vapor/Grid.h:1217]: It will do the right thing, but you might want to  look at the code and the documentation to convince yourself.

File: lib/vdc/ConstantGrid.cpp (hunk 1 above)
Comment (clyne) [reply lib/vdc/ConstantGrid.cpp:42]: @shaomeng I'd like the code to be consistent. We have a developer-defined type for all of these 3-element array arguments, please use it. If you really have a problem with the naming of the type you are more than welcome to change it.

File: include/vapor/ConstantGrid.h (hunk 2 above)
Comment (clyne) [reply include/vapor/ConstantGrid.h:53]: OK. Any idea why? I.e. our entire code base was supposed to be consistently formatted with clang-format. Do you have any idea why clang-format decided to re-format this unchanged code now?

File: include/vapor/Grid.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (shaomeng) [reply include/vapor/Grid.h]: Got it, fixed in 52081bac1

File: lib/vdc/ConstantGrid.cpp (hunk 1 above)
Comment (shaomeng) [reply lib/vdc/ConstantGrid.cpp:42]: Ok, I've renamed the alias in 52081bac1 with two of them: `DimsType` and `CoordType`. Two notes:
1. It's common practice to have a word "type" at the end of all alias, so when people see it people know it's an alias that redefines something else.
2. It's also common to name alias after its semantic meaning, (Dims and Coord in this example), so the following function signature is very easy to understand:
```c++
void function( DimsType, CoordType );

File: lib/vdc/StructuredGrid.cpp [hunk 4]
```diff
@@ -34,6 +34,10 @@ StructuredGrid::StructuredGrid(const vector<size_t> &dims, const vector<size_t>
     }
 }
 
+const std::array<size_t, 3> StructuredGrid::GetNodeDimensions() const { return GetDimensions(); }
```
[the remark this answers is not in the document]
Comment (shaomeng) [reply lib/vdc/StructuredGrid.cpp:37]: fixed in 52081bac1

File: include/vapor/ConstantGrid.h (hunk 2 above)
Comment (shaomeng) [reply include/vapor/ConstantGrid.h:53]: There was one function signature change, which resulted a longer line. Clang-format tries to align all function names, so it shifted all function signatures, resulting the changes we see here.

File: include/vapor/UnstructuredGrid.h [hunk 5]
```diff
@@ -127,23 +127,24 @@ class VDF_API UnstructuredGrid : public Grid {
...
+    virtual bool GetNodeCells(const DimsType &indices, std::vector<DimsType> &cells) const override;
 
     size_t GetMaxVertexPerFace() const override { return (_maxVertexPerFace); };
 
     size_t GetMaxVertexPerCell() const override { return ((GetTopologyDim() == 3) ? 2 * GetMaxVertexPerFace() : GetMaxVertexPerFace()); };
 
     //! Return the grid node dimmensions
     //!
-    const std::vector<size_t> &GetNodeDimensions() const override { return (_vertexDims); }
+    const std::array<size_t, 3> GetNodeDimensions() const override;
```
Comment (clyne) [inline include/vapor/UnstructuredGrid.h:146]: Shouldn't this be DimsType?

Comment (shaomeng) [reply include/vapor/UnstructuredGrid.h]: You're right. Fixed this one together with a few others that were missed.

File: lib/vdc/ConstantGrid.cpp (hunk 1 above)
Comment (clyne) [reply lib/vdc/ConstantGrid.cpp]: That's fine by me. FYI it is also common practice to designate types with "_t" suffix. E.g. size_t, uint_t, etc.

File: include/vapor/ConstantGrid.h (hunk 2 above)
Comment (clyne) [reply include/vapor/ConstantGrid.h:53]: Got it. Thanks. Not sure I like that feature, but I can live with it :-)

**Review by clyne — APPROVED** [review]
