### PR TITLE
Fix #1748: Transforms: First loaded dataset gets ignored

### LINKED ISSUE #1748: Transforms: First loaded dataset gets ignored
To reproduce:

1) Load any WRF VDC dataset
2) Import one if its WRF source files
3) In the Navigation->Viewpoint tab, scale the VDC dataset by 30 on Z
4) Move the scene, and the scale factor will revert to its previous value
5) Scale the imported dataset, and the transform will be honored

### PR DESCRIPTION
**Pull request by StasJ**
Fix #1748 

There was some code in the annotation renderer that was breaking the dataset scaling

### CODE REVIEW

File: lib/render/AnnotationRenderer.cpp [hunk 1]
```diff
@@ -514,14 +514,6 @@ void AnnotationRenderer::InScenePaint(size_t ts)
...
 	vector<string> names = m_paramsMgr->GetDataMgrNames();
     Transform* t = vpParams->GetTransform(names[0]);
-    if (names.size()) {
-        Transform* tmp;
-        for (int i=0; i<names.size(); i++) {
-            tmp = vpParams->GetTransform(names[i]);
-            if ( tmp->GetScales()[Z] < t->GetScales()[Z] )
-                *t = *tmp;
-        }
-    }
```
Comment (sgpearse) [inline lib/render/AnnotationRenderer.cpp]: I believe this will reintroduce issue #1214 

In retrospect, I should have commented this code though.  It's taking the smallest z scale factor from all datasets, and using that is the default.  If a ROMS default scale factor is 1000, this will blow up the scene if it's loaded alongside of a WRF dataset.

Comment (StasJ) [reply lib/render/AnnotationRenderer.cpp]: I don't quite understand that bug. It says "[if auto scaling is enabled ... step 1: make sure auto scaling is disabled]"

How would this fix that bug? The annotation renderer shouldn't fix the renderers' scaling factors?

Comment (sgpearse) [reply lib/render/AnnotationRenderer.cpp]: What this code is doing is 

1) Gather the default scale factors for all of the data managers
2) Select the smallest scale factor, and apply that to the ViewpointParams

Say we loaded an ocean model with a default scale factor of 1000, and an atmospheric model with a scale factor of 50. 

When we randomly take the scale factor associated with names[0], we could be applying the ocean model 1000x scale.  This makes the atmospheric domain too big, and unusable.  

Therefore we look at all scale factors, and use the smallest one for the ViewpointParams.

**Comment by clyne** [comment]
@sgpearse you approved the PR, but the conversation has not been marked "resolved". Is it resolved?

File: lib/render/AnnotationRenderer.cpp (hunk 1 above)
Comment (clyne) [reply lib/render/AnnotationRenderer.cpp]: @sgpearse you have approved this PR, but it's not clear that your concern regarding a regression has been addressed: "I believe this will reintroduce issue #1214". Has it been addressed?

Comment (sgpearse) [reply lib/render/AnnotationRenderer.cpp]: I went ahead tested this branch to see if #1214 had regressed, but I wasn't able to reproduce it.  Since there's no regression, I approved the PR.

**Comment by sgpearse** [comment]
@clyne I went ahead tested this branch to see if #1214 had regressed, but I wasn't able to reproduce it. Since there's no regression, I approved the PR.
