### PR TITLE
New3rd party libraries

### LINKED ISSUE #2816: Enable support for reading NetCDF files compressed with ZFP, and possibly other compressors
Rebuild our 3rd party NetCDF library with support for reading CF compliant NetCDF files that contain variables compressed with ZFP (and possibly other compressors). This may be non-trivial. See discussion here:

https://github.com/Unidata/netcdf-c/issues/1545

### LINKED ISSUE #3158: OSX build broken on CircleCI
Weekly install is no longer being published due to failure on OSX.

https://app.circleci.com/pipelines/github/NCAR/VAPOR/5813/workflows/ae15eff8-8f45-4ff8-84c9-cb1698c157af/jobs/13821

### LINKED ISSUE #3174: Image renderer crash on geotiff
1) On OSX - Import any WRF file
2) Create and enable an image renderer with the attached geotiff (zipped upon github's demand)
3) Vapor will crash

Note: Upgrading to libgeotiff 1.7.1 fixes this, and will be addressed in PR #3110
[snapshot-2021-12-28T00_00_00Z (1).tiff.zip](https://github.com/NCAR/VAPOR/files/9302548/snapshot-2021-12-28T00_00_00Z.1.tiff.zip)

### LINKED ISSUE #3179: Can't compiler lib/osgl with OpenMP enabled on OSX
Compiling with OpenMP support  on OSX requires using the vanilla clang compiler (not Apple's bundled bastardization of clang). Compilation is failing as shown below:
```

[ 10%] Building C object lib/osgl/CMakeFiles/osgl.dir/glad/src/egl.c.o
In file included from /Users/clyne/src/vapor/lib/osgl/GLContextProviderMacOS.mm:2:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSOpenGL.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:91:143: error: function does not return NSString
- (NSAttributedString *)localizedAttributedStringForKey:(NSString *)key value:(nullable NSString *)value table:(nullable NSString *)tableName NS_FORMAT_ARGUMENT(1) NS_REFINED_FOR_SWIFT API_AVAILABLE(macos(12.0), ios(15.0), watchos(8.0), tvos(15.0));

```

```
cisl-benona[611] clang --version
clang version 12.0.1
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /opt/local/libexec/llvm-12/bin

```

I believe that this issue is related to #3158

Clearly we have to fix this to release. Giving the issue a milestone and assigning to @StasJ

### PR DESCRIPTION
**Pull request by sgpearse**
This PR updates Vapor to use ZFP enabled HDF5 and an updated version of Ospray. Users must set the HDF5_PLUGIN_PATH to Vapor's /lib directory to allow for ZFP enabled compression.

Since not all libraries were rebuilt, the newly built libraries had to be targeted at /usr/local/VAPOR-Deps/2019-Aug again.

The new libraries can be found on [google drive](https://drive.google.com/drive/u/0/folders/0B0dQMtxB89M0Q2F2U3ZaQ2dVeWs?resourcekey=0-KjrYiMNi3FG-JnLKuDFupw). They have been named 2019-Aug-[OS]-2022.tar.xz

Links here:
[Ubuntu](https://drive.google.com/file/d/1CD3qrPuj03S8x1XshDI_3GRqCeUVLvpm/view?usp=sharing)
[CentOS](https://drive.google.com/file/d/1In3Q8fA0VCm2en1ncBQI6dzUfatLDA0y/view?usp=sharing)
[OSX](https://drive.google.com/file/d/1KnUoBfOLuF6VJMXG6KcljjKMpr4VGxQ6/view?usp=sharing)
[Windows](https://drive.google.com/file/d/1fzZ-mbY4Cek1TRsaKm79a08Od5gNCogk/view?usp=sharing)

d4810cbbaa453e7af67529a32c104f396c22f466: [clangTidyOutput.txt](https://output.circle-artifacts.com/output/job/94eb3331-1df6-43c6-8f15-087b54654043/artifacts/0/tmp/clangTidyOutput.txt)

Fixes #3179 
Fixes #3158 
Fixes #3174 
Fixes #2816

### CODE REVIEW

**Comment by shaomeng** [comment]
Hi Scott, do you mind updating the `glm` library too? It's a header-only library so should be easy to deal with, yet updating it is aligned with our ultimate goal.

**Comment by clyne** [comment]
@sgpearse can you please identify which libraries were updated and their version numbers?

**Comment by sgpearse** [comment]
@all - HDF5 seems to be working on Windows now.  I'll request re-reviews once I can verify that the build systems are referencing the new libraries.  Answers to your questions are below.

> Hi Scott, do you mind updating the glm library too?

@shaomeng - No problem.

> @sgpearse can you please identify which libraries were updated and their version numbers?

@clyne 
HDF5 - 1.12.2
HDF5 Plugins - 1.12.2
NetCDF - 4.8.1
Ospray - 2.9.0
GLM - 0.9.9.8

> Is there a reason we will require users to manually set HDF5_PLUGIN_PATH to enable ZFP?

@StasJ - From what I've read, this is necessary.  From the [NetCDF documentation](https://github.com/Unidata/netcdf-c/blob/main/docs/filters.md#filters_appendixb):

> At the moment, NetCDF uses the existing HDF5 environment variable HDF5_PLUGIN_PATH to locate the directories in which filter wrapper shared libraries are located. This is used both for the HDF5 filter wrappers but also the NCZarr codec wrappers.

There [may be a way to use HDF5's API](https://zditect.com/blog/54122394.html) for this but I'm not sure what it entails.

**Comment by sgpearse** [comment]
Installers have been verified on all platforms with the new libraries.  If you'd like to try the installers, you can find them in the artifacts on [these builds](https://app.circleci.com/pipelines/github/NCAR/VAPOR/5765/workflows/b046deb7-e136-4985-8154-38d4988c47d7).

@stasj I was able to remove the need for HDF5_PLUGIN_PATH on our UNIX systems.  I had no luck building SZlib+HDF5+NetCDF together, so I used Unidata's NetCDF binary installer for Windows.  This leaves us without the HDF5 library needed to make the programmatic call for finding the plugin path.

@stasj and @clyne - the programatic call for setting the HDF5 plugin path is currently in apps/vaporgui/main.cpp.  Should this be moved elsewhere?

**Comment by clyne** [comment]
> 

@sgpearse it looks to me like you are calling H5PLreplace() on Mac and Linux platforms, not windows. I'm a little confused because I thought you only need to set the plug path explicitly on Windows systems?

Regardless, setting the path in the vaporgui app. is probably not ideal; our conversion utilities won't work. Any thoughts on this @stasj? I'm not sure if it is a disaster if we can't convert to/from hdf5 to VDC on Windows platforms. We may just have to live with that.

**Review by StasJ — COMMENTED** [review]
> @sgpearse it looks to me like you are calling H5PLreplace() on Mac and Linux platforms, not windows. I'm a little confused because I thought you only need to set the plug path explicitly on Windows systems?
> 
> Regardless, setting the path in the vaporgui app. is probably not ideal; our conversion utilities won't work. Any thoughts on this @StasJ? I'm not sure if it is a disaster if we can't convert to/from hdf5 to VDC on Windows platforms. We may just have to live with that.

Couldn’t we just set the plugin path in the VDC API when attempting to load an HDF5 dataset? We could keep track of whether it had been set or the HDF5 API allows you to query the existing plugin paths.

**Comment by clyne** [comment]
> Couldn’t we just set the plugin path in the VDC API when attempting to load an HDF5 dataset? We could keep track of whether it had been set or the HDF5 API allows you to query the existing plugin paths.

That could be done, but to ensure all of our readers and writers that access NetCDF files (e.g. DCMPAS, DCWRF, VDNetCDF, etc.) are supported we would have to do this in multiple places; there is not one single place where NetCDF is initialized, unfortunately. 

Another option might be to not touch the code, and to instead set the HDF5_PLUGIN_PATH. It looks like HDF5 will honor that. I don't what is involved in setting an env variable for our Windows installer.

**Comment by clyne** [comment]
> Here's an idea: in case that we have to distribute VAPOR with different capabilities among 3 major platforms, or even capabilities that are easy to go wrong within the camp of Linux for example, we provide a utility program that detects those variables and report to the user. It could be some added fields to "vaporversion".
The following capabilities can be subject to detection and report:

Whether ZFP (or any other) compression is supported
Whether OpenMP is supported
On tricky grids, whether GPU accelerated DVR is supported

Good idea, @shaomeng. Could you open an issue?

**Comment by shaomeng** [comment]
>
> Good idea, @shaomeng. Could you open an issue?

Sure. #3142 is opened now.

**Comment by sgpearse** [comment]
> @sgpearse we need seem clarification. Does the HDF5 plugin path need to be explicitly set on all platforms?

HDF5_PLUGIN_PATH only needs to be set on Windows.  It also needs to be set on our personal development machines because GetResourcePath() only works on installed versions of Vapor.  It does not return /usr/local/VAPOR-Deps/2019-Aug during development builds.

**Comment by StasJ** [comment]
> > @sgpearse we need seem clarification. Does the HDF5 plugin path need to be explicitly set on all platforms?
> 
> HDF5_PLUGIN_PATH only needs to be set on Windows. It also needs to be set on our personal development machines because GetResourcePath() only works on installed versions of Vapor. It does not return /usr/local/VAPOR-Deps/2019-Aug during development builds.

`GetResourcePath()` does work on development builds. Otherwise many other features such as rendering maps wouldn't work.

**Comment by sgpearse** [comment]
@stasj I see it now, thank you.

HDF5_PLUGIN_PATH is now only required on **windows** dev/installer builds.

**Comment by sgpearse** [comment]
@stasj _putenv() is doing the trick on Windows now, so there's now no need to manually set HDF5_PLUTIN_PATH on any platform.

File: lib/vdc/NetCDFSimple.cpp [hunk 1]
```diff
@@ -200,7 +200,10 @@ int NetCDFSimple::Read(const size_t start[], const size_t count[], float *data,
 
     int rc = nc_get_vara_float(_ncid, varid, start, count, data);
     if (rc != 0) {
-        SetErrMsg("nc_get_vara_float(%d, %d) : %s", _ncid, varid, nc_strerror(rc));
+        std::string error = nc_strerror(rc);
+        if (error.find("NetCDF: Filter error: unimplemented filter encountered") != std::string::npos)
+            SetErrMsg("\nHave you set the environment variable HDF5_PLUGIN_PATH to Vapor's /lib directory?\n");
```
[the remark this answers is not in the document]
Comment (sgpearse) [reply lib/vdc/NetCDFSimple.cpp:205]: Sure, I'll remove it.

File: apps/vaporgui/CMakeLists.txt [hunk 2]
```diff
@@ -379,7 +381,7 @@ endif()
 
 target_link_libraries (
         vapor common vdc wasp render params jpeg ${GLEW} 
-        ${TIFF_LIB} geotiff ${ASSIMP_LIB} Qt5::Widgets Qt5::OpenGL Qt5::Core Qt5::Gui Qt5::DBus Qt5::Network
+        ${HDF5_LIB} ${TIFF_LIB} geotiff ${ASSIMP_LIB} Qt5::Widgets Qt5::OpenGL Qt5::Core Qt5::Gui Qt5::DBus Qt5::Network
```
[the remark this answers is not in the document]
Comment (StasJ) [reply apps/vaporgui/CMakeLists.txt:384]: So the GUI will support ZFP data but our command line utilities won't?

File: apps/vaporgui/main.cpp [hunk 3]
```diff
@@ -171,9 +174,17 @@ int           main(int argc, char **argv)
...
     MyBase::SetDiagMsg("PYTHONHOME = %s", phome.c_str());
-
 #endif
 
+// Programatically set the hdf5 plugin path
+#ifndef WIN32
+	string plugins = Wasp::GetResourcePath("lib/hdf/HDF_Group/HDF5/1.12.2/lib/plugin");
+	H5PLreplace(plugins.c_str(), 0);
+#else
+    string envVar = "HDF5_PLUGIN_PATH=" + Wasp::GetResourcePath("plugin");
```
[the remark this answers is not in the document]
Comment (StasJ) [reply apps/vaporgui/main.cpp]: The .so files should be configured so that they can be moved. If you look at the installer generator code, it ensures that our third party libraries are moveable.

**Review by shaomeng — APPROVED** [review]
I assume when we run data set tests, any problem with netCDF could be unearthed.

**Comment by clyne** [comment]
@sgpearse pinging you that there are unresolved comments here before we can close.

File: apps/vaporgui/main.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (sgpearse) [reply apps/vaporgui/main.cpp]: You're right, that worked.  The plugins are now in share/plugins.

File: apps/vaporgui/CMakeLists.txt (hunk 2 above)
[the remark this answers is not in the document]
Comment (sgpearse) [reply apps/vaporgui/CMakeLists.txt]: Fixed - netcdf, and wrf utilites now link to the hdf5 plugins.

**Comment by sgpearse** [comment]
Sorry - I've been seeing some of my comments not register on github recently.  Not sure what the cause is yet.

The only thing I'm concerned about is that I haven't tested this on the current main branch with windows - only main, pre python api.

File: lib/common/CMakeLists.txt [hunk 4]
```diff
@@ -43,7 +43,8 @@ set (HEADERS
 	${PROJECT_SOURCE_DIR}/include/vapor/Base16StringStream.h
 )
 
-add_library (common SHARED ${SRC} ${HEADERS})
+find_library(HDF5_LIB hdf5)
```
Comment (StasJ) [inline lib/common/CMakeLists.txt:46]: Libraries used by the entire package are found together at the top level CMakeLists.txt

File: lib/common/CMakeLists.txt [hunk 5]
```diff
@@ -43,7 +43,8 @@ set (HEADERS
...
+add_library (common SHARED ${SRC} ${HEADERS} ${HDF5_LIB})
```
Comment (StasJ) [inline lib/common/CMakeLists.txt:47]: Libraries aren't valid arguments to `add_library`

File: lib/common/CMakeLists.txt [hunk 6]
```diff
@@ -68,6 +69,8 @@ target_include_directories (common
 	PUBLIC "${THIRD_PARTY_INC_DIR}/freetype2"
 	)
 
+#target_link_libraries(${HDF5_LIB})
+
```
Comment (StasJ) [inline lib/common/CMakeLists.txt:73]: Leftover unused code.

File: lib/common/ResourcePath.cpp [hunk 7]
```diff
@@ -128,6 +132,18 @@ std::string Wasp::GetPythonDir()
     return path;
 }
 
+void Wasp::SetHDF5PluginPath() {
+    string plugins = Wasp::GetResourcePath("share/plugins");
```
Comment (StasJ) [inline lib/common/ResourcePath.cpp:136]: This should call `Wasp::GetSharePath`

File: lib/common/ResourcePath.cpp [hunk 8]
```diff
@@ -128,6 +132,18 @@ std::string Wasp::GetPythonDir()
...
+
+#ifndef WIN32
+    H5PLreplace(plugins.c_str(), 0);
+#else
+    plugins = "HDF5_PLUGIN_PATH=" + plugins;
+    int rc=_putenv(plugins.c_str());
+    if (rc != 0) MyBase::SetDiagMsg("Unable to set environtment variable %s", plugins.c_str());
```
Comment (StasJ) [inline lib/common/ResourcePath.cpp:143]: Should this be a warning rather than a diagnostic message? I don't think the user ever sees our diagnostic messages.

File: lib/vdc/NetCDFSimple.cpp [hunk 9]
```diff
@@ -200,7 +200,8 @@ int NetCDFSimple::Read(const size_t start[], const size_t count[], float *data,
 
     int rc = nc_get_vara_float(_ncid, varid, start, count, data);
     if (rc != 0) {
-        SetErrMsg("nc_get_vara_float(%d, %d) : %s", _ncid, varid, nc_strerror(rc));
+        std::string error = nc_strerror(rc);
+        SetErrMsg("nc_get_vara_float(%d, %d) : %s", _ncid, varid, error.c_str());
```
Comment (StasJ) [inline lib/vdc/NetCDFSimple.cpp:204]: `nc_strerror` already returns a `const char *`?

**Review by StasJ — COMMENTED** [review]
This change requires lib common to link against HDF5. It may be more appropriate for the VDC library to handle this since it handles the use HDF5 files.

**Comment by clyne** [comment]
Fixes #2816

File: lib/common/CMakeLists.txt (hunk 4 above)
Comment (sgpearse) [reply lib/common/CMakeLists.txt]: Thanks, fixed.

File: lib/common/CMakeLists.txt (hunk 5 above)
Comment (sgpearse) [reply lib/common/CMakeLists.txt]: You're correct.  Fixed.

File: lib/common/CMakeLists.txt (hunk 6 above)
Comment (sgpearse) [reply lib/common/CMakeLists.txt]: Fixed.

File: lib/common/ResourcePath.cpp (hunk 7 above)
Comment (sgpearse) [reply lib/common/ResourcePath.cpp]: Thanks, fixed.

File: lib/common/ResourcePath.cpp (hunk 8 above)
Comment (sgpearse) [reply lib/common/ResourcePath.cpp]: Good point.  Fixed.

File: lib/vdc/NetCDFSimple.cpp (hunk 9 above)
Comment (sgpearse) [reply lib/vdc/NetCDFSimple.cpp]: Fixed.

**Comment by sgpearse** [comment]
@stasj - Your notes should be addressed.  All installers are working except for Windows, #3178.  osgl seems to be the problem when we build with the gui.  The broken windows build is reported #3178.

**Review by StasJ — COMMENTED** [review]
> @StasJ - Your notes should be addressed. All installers are working except for Windows, https://github.com/NCAR/VAPOR/issues/3178. osgl seems to be the problem when we build with the gui. The broken windows build is reported https://github.com/NCAR/VAPOR/issues/3178.

Thanks, looks great. There was one comment you didn't respond to:

> This change requires lib-common to link against HDF5. It may be more appropriate for the VDC library to handle this since it handles the use of HDF5 files.

**Comment by sgpearse** [comment]
@Stasj - Ah, I did miss that.  I thought lib common made sense because it handles our resource paths, but no biggie.  Fixed.

**Comment by sgpearse** [comment]
Fixes #3179.

**Comment by sgpearse** [comment]
Fixes #3158.

**Comment by sgpearse** [comment]
Fixes #3174

**Comment by clyne** [comment]
Ready for @stasj to review again

**Comment by clyne** [comment]
Fixes #2816

**Review by StasJ — APPROVED** [review]

**Comment by clyne** [comment]
@sgpearse this issue has been closed. Presumably everyone should update their own development libraries to be in sync with the DevOps platforms, correct? Where are these libraries available?

thanks!

cc: @NihanthCW @shaomeng @StasJ

**Comment by sgpearse** [comment]
> Presumably everyone should update their own development libraries to be in sync with the DevOps platforms, correct? 

Yes.

> Where are these libraries available?

Check out the PR description, which has links to bundles for each platform.

**Comment by clyne** [comment]
When I click on the link for Mac OSX I get: 

Sorry, the file you have requested does not exist.

**Comment by sgpearse** [comment]
@clyne Broken link is updated on OSX [here](https://drive.google.com/file/d/1Q-IXlP_OgZSXsWKmT-smyrW9xnR-dUfg/view?usp=sharing).  PS - I've double checked that the links on CircleCI are targeting the correct libraries and not dead links.
