### PR TITLE
Fixes #2536 - Vapor hangs with some WRF-Fire data sets

### LINKED ISSUE #2536: Vapor hangs with some WRF-Fire data sets
Hi everybody,

I am trying to visualize some WRF-Fire idealized simulation output using Vapor 3.2. However, when I want to create barb renderer or some other renderers Vapor hangs and I have to force quit it! The WRF output file is relatively small, about 160 mb. and also only Wireframe renderer works correctly.

I am using WRF version 4.2 and Vapor version 3.1 on my MacBook Pro 16 running Catalina.

I appreciate every help, and thank you very much in advance!

**Helpful additional information**
(*Please click check boxes AFTER submitting ticket*)
- [*] Did VAPOR crash?
- [ ] Did you get wrong results?

**Impact**
- [*] High - User productivity significantly degraded
- [ ] Medium - User productivity partially degraded
- [ ] Low - User productivity trivially degraded

### Desktop
 - OS and version: macOS Catalina 10.15.5
 - Version: Vapor 3.2

### PR DESCRIPTION
**Pull request by clyne**
Fixes #2536 

Note: the test data are now on glade in WRF/WRF-Fire/kasrash

### CODE REVIEW

File: lib/vdc/DCWRF.cpp [hunk 1]
```diff
@@ -748,42 +748,38 @@ int DCWRF::_GetProj4String(
...
+	ncdfc->Close(fd);
 
-		for (size_t i=0; i<Wasp::VProduct(dims)-1; i++) {
-			if (data[i] != data[i+1]) {
-				EnableErrMsg(enabled);
-				return(false);
-			}
+	for (size_t i=0; i<Wasp::VProduct(dims)-1; i++) {
+		if (data[i] != data[i+1]) {
+			EnableErrMsg(enabled);
```
Comment (StasJ) [inline lib/vdc/DCWRF.cpp:781]: Do we want to account for "almost constant" since these are floats? Also, performance can be improved by comparing all values against the first.

**Review by StasJ — APPROVED** [review]

File: lib/vdc/DCWRF.cpp (hunk 1 above)
Comment (clyne) [reply lib/vdc/DCWRF.cpp:781]: Hmm. I think doing "almost constant" correctly would be expensive and might be overkill. You'd have to compare every value with every other value, wouldn't you? Consider

`a ~= b && b ~= c`

does not imply

`a ~= c`

Comment (StasJ) [reply lib/vdc/DCWRF.cpp:781]: I don't think you would have to do that. a_0 ~= x in [a_1..a_n] implies the field is constant.

Comment (clyne) [reply lib/vdc/DCWRF.cpp:787]: You are correct. Done.

**Review by StasJ — APPROVED** [review]

**Review by sgpearse — APPROVED** [review]
